name: Express App Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # No need for PostgreSQL service, just run Express

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the Express app
      - name: Start Express app
        run: |
          nohup npm start & # Start the Express server in the background

      # Run Postman tests
      - name: Run Postman tests
        uses: actions/postman/run-postman-action@v2
        with:
          collection: path/to/your/postman_collection.json
          environment: path/to/your/postman_environment.json
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}  # Set Postman API key from GitHub secrets
